name: APIOps Extractor Pipeline

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install jq
        npm install -g @azure/arm-apimanagement

    - name: Extract full APIM configuration using ARM template
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        APIM_NAME: ${{ secrets.APIM_NAME }}
      run: |
        APIOPS_EXTRACTOR_DIR=apiops-extractor
        mkdir -p $APIOPS_EXTRACTOR_DIR
        echo "Extracting APIM configuration using ARM template..."

        # Export the APIM instance as an ARM template
        az apim export --name $APIM_NAME --resource-group $RESOURCE_GROUP --output-folder $APIOPS_EXTRACTOR_DIR --output-format arm-template

    - name: Commit and push extracted configurations
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add apiops-extractor/*
        git commit -m "Extracted full APIM configuration"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
        git push origin main
